# Generated by Django 4.2.7 on 2023-12-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0002_user_remove_file_author_file_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="content",
            field=models.FileField(blank=True, null=True, upload_to="images/"),
        ),
    ]
