# Generated by Django 4.2.7 on 2023-12-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0003_alter_file_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="user_id",
            field=models.CharField(default="", max_length=225),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(max_length=225, primary_key=True, serialize=False),
        ),
    ]
