# Generated by Django 4.2.7 on 2023-12-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0004_alter_file_user_id_alter_user_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
