# Generated by Django 4.2.7 on 2023-12-15 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0005_alter_file_content"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
        migrations.RenameField(
            model_name="file",
            old_name="user_id",
            new_name="username",
        ),
    ]
