# Generated by Django 4.2.7 on 2023-12-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0006_delete_user_rename_user_id_file_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="content",
            field=models.TextField(),
        ),
    ]
